[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/data.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/elite"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/elite/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lineas-originales"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lineas-originales/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/club-jeans"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/club-jeans/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/miguel-aleman"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/miguel-aleman/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/almacen-general"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/almacen-general/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/zapotlanejo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/zapotlanejo/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/denim-click"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/denim-click/"
  to = "/index.html"
  status = 200
